
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
  namespace: default
  resourceVersion: "1"
data:
  POSTGRES_DB: example
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  DB_SERVICE: postgres-service
  DB_PORT: "5432"