apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-sdc
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /usr/share/nginx
