apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
  labels:
    run: web-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: nhatthai/mysite_django2.1:latest
        ports:
        - containerPort: 8000
          protocol: TCP
